using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

class DebugWalker : CSharpSyntaxWalker 
{
    const string INDENT_STRING = "  ";
    int indent = 0;

    public DebugWalker(SyntaxTree tree) : base(SyntaxWalkerDepth.Trivia)
    {
        Visit(tree.GetRoot());
    }

    void printline(string format, params Object?[]? args) 
    {
        Console.Write(INDENT_STRING.Repeat(indent));
        Console.Write(format, args);
        Console.WriteLine();
    }

    public override void VisitTrivia(SyntaxTrivia trivia)
    {
        switch (trivia.Kind()) {
            case SyntaxKind.XmlComment: {
                throw new NotSupportedException("XmlComment not supported as we don't know when/if those are generated by the parser.");
            }

            case SyntaxKind.SingleLineCommentTrivia:
            case SyntaxKind.SingleLineDocumentationCommentTrivia:
            case SyntaxKind.MultiLineCommentTrivia:
            case SyntaxKind.MultiLineDocumentationCommentTrivia: {
                printline("Comment: {0}", trivia.ToFullString().ReplaceLineEndings("¬").Truncate(60));
                break;
            }

            case SyntaxKind.EndOfLineTrivia: {
                printline("¬");
                break;
            }
        }
    }

    public override void DefaultVisit(SyntaxNode node)
    {
        switch(node) {
            case MethodDeclarationSyntax  s: printline("«{0} {1}»", node.GetType().Name, s.Identifier.Text); break;
            case ClassDeclarationSyntax   s: printline("«{0} {1}»", node.GetType().Name, s.Identifier.Text); break;
            case GenericNameSyntax        s: printline("«{0} {1}»", node.GetType().Name, s.Identifier.Text); break;
            case IdentifierNameSyntax     s: printline("«{0} {1}»", node.GetType().Name, s.Identifier.Text); break;
            case ParameterSyntax          s: printline("«{0} {1}»", node.GetType().Name, s.Identifier.Text); break;
            case SimpleNameSyntax         s: printline("«{0} {1}»", node.GetType().Name, s.Identifier.Text); break;
            case VariableDeclaratorSyntax s: printline("«{0} {1}»", node.GetType().Name, s.Identifier.Text); break;
            default: printline("«{0}»", node.GetType().Name); break;
        }
        indent++;
        base.DefaultVisit(node);
        indent--;
    }

}
